# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CWAStats.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='CWAStats.proto',
  package='CWAConfig',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x43WAStats.proto\x12\tCWAConfig\"/\n\nCardHeader\x12\x0e\n\x06\x63\x61rdId\x18\x01 \x01(\x05\x12\x11\n\tupdatedAt\x18\x02 \x01(\x03\"`\n\rKeyFigureCard\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.CWAConfig.CardHeader\x12(\n\nkeyFigures\x18\x02 \x03(\x0b\x32\x14.CWAConfig.KeyFigure\"\xa9\x03\n\tKeyFigure\x12\'\n\x04rank\x18\x01 \x01(\x0e\x32\x19.CWAConfig.KeyFigure.Rank\x12\r\n\x05value\x18\x02 \x01(\x01\x12\x10\n\x08\x64\x65\x63imals\x18\x03 \x01(\x05\x12)\n\x05trend\x18\x04 \x01(\x0e\x32\x1a.CWAConfig.KeyFigure.Trend\x12\x39\n\rtrendSemantic\x18\x05 \x01(\x0e\x32\".CWAConfig.KeyFigure.TrendSemantic\"F\n\x04Rank\x12\x14\n\x10UNSPECIFIED_RANK\x10\x00\x12\x0b\n\x07PRIMARY\x10\x01\x12\r\n\tSECONDARY\x10\x02\x12\x0c\n\x08TERTIARY\x10\x03\"J\n\x05Trend\x12\x15\n\x11UNSPECIFIED_TREND\x10\x00\x12\n\n\x06STABLE\x10\x01\x12\x0e\n\nINCREASING\x10\x02\x12\x0e\n\nDECREASING\x10\x03\"X\n\rTrendSemantic\x12\x1e\n\x1aUNSPECIFIED_TREND_SEMANTIC\x10\x00\x12\x0b\n\x07NEUTRAL\x10\x01\x12\x0c\n\x08POSITIVE\x10\x02\x12\x0c\n\x08NEGATIVE\x10\x03\"V\n\nStatistics\x12\x16\n\x0e\x63\x61rdIdSequence\x18\x01 \x03(\x05\x12\x30\n\x0ekeyFigureCards\x18\x02 \x03(\x0b\x32\x18.CWAConfig.KeyFigureCardb\x06proto3')
)



_KEYFIGURE_RANK = _descriptor.EnumDescriptor(
  name='Rank',
  full_name='CWAConfig.KeyFigure.Rank',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSPECIFIED_RANK', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRIMARY', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SECONDARY', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TERTIARY', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=366,
  serialized_end=436,
)
_sym_db.RegisterEnumDescriptor(_KEYFIGURE_RANK)

_KEYFIGURE_TREND = _descriptor.EnumDescriptor(
  name='Trend',
  full_name='CWAConfig.KeyFigure.Trend',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSPECIFIED_TREND', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STABLE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INCREASING', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DECREASING', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=438,
  serialized_end=512,
)
_sym_db.RegisterEnumDescriptor(_KEYFIGURE_TREND)

_KEYFIGURE_TRENDSEMANTIC = _descriptor.EnumDescriptor(
  name='TrendSemantic',
  full_name='CWAConfig.KeyFigure.TrendSemantic',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSPECIFIED_TREND_SEMANTIC', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NEUTRAL', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POSITIVE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NEGATIVE', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=514,
  serialized_end=602,
)
_sym_db.RegisterEnumDescriptor(_KEYFIGURE_TRENDSEMANTIC)


_CARDHEADER = _descriptor.Descriptor(
  name='CardHeader',
  full_name='CWAConfig.CardHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cardId', full_name='CWAConfig.CardHeader.cardId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='updatedAt', full_name='CWAConfig.CardHeader.updatedAt', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=76,
)


_KEYFIGURECARD = _descriptor.Descriptor(
  name='KeyFigureCard',
  full_name='CWAConfig.KeyFigureCard',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='CWAConfig.KeyFigureCard.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='keyFigures', full_name='CWAConfig.KeyFigureCard.keyFigures', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=174,
)


_KEYFIGURE = _descriptor.Descriptor(
  name='KeyFigure',
  full_name='CWAConfig.KeyFigure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rank', full_name='CWAConfig.KeyFigure.rank', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='CWAConfig.KeyFigure.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='decimals', full_name='CWAConfig.KeyFigure.decimals', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trend', full_name='CWAConfig.KeyFigure.trend', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trendSemantic', full_name='CWAConfig.KeyFigure.trendSemantic', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _KEYFIGURE_RANK,
    _KEYFIGURE_TREND,
    _KEYFIGURE_TRENDSEMANTIC,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=602,
)


_STATISTICS = _descriptor.Descriptor(
  name='Statistics',
  full_name='CWAConfig.Statistics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cardIdSequence', full_name='CWAConfig.Statistics.cardIdSequence', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='keyFigureCards', full_name='CWAConfig.Statistics.keyFigureCards', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=604,
  serialized_end=690,
)

_KEYFIGURECARD.fields_by_name['header'].message_type = _CARDHEADER
_KEYFIGURECARD.fields_by_name['keyFigures'].message_type = _KEYFIGURE
_KEYFIGURE.fields_by_name['rank'].enum_type = _KEYFIGURE_RANK
_KEYFIGURE.fields_by_name['trend'].enum_type = _KEYFIGURE_TREND
_KEYFIGURE.fields_by_name['trendSemantic'].enum_type = _KEYFIGURE_TRENDSEMANTIC
_KEYFIGURE_RANK.containing_type = _KEYFIGURE
_KEYFIGURE_TREND.containing_type = _KEYFIGURE
_KEYFIGURE_TRENDSEMANTIC.containing_type = _KEYFIGURE
_STATISTICS.fields_by_name['keyFigureCards'].message_type = _KEYFIGURECARD
DESCRIPTOR.message_types_by_name['CardHeader'] = _CARDHEADER
DESCRIPTOR.message_types_by_name['KeyFigureCard'] = _KEYFIGURECARD
DESCRIPTOR.message_types_by_name['KeyFigure'] = _KEYFIGURE
DESCRIPTOR.message_types_by_name['Statistics'] = _STATISTICS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CardHeader = _reflection.GeneratedProtocolMessageType('CardHeader', (_message.Message,), dict(
  DESCRIPTOR = _CARDHEADER,
  __module__ = 'CWAStats_pb2'
  # @@protoc_insertion_point(class_scope:CWAConfig.CardHeader)
  ))
_sym_db.RegisterMessage(CardHeader)

KeyFigureCard = _reflection.GeneratedProtocolMessageType('KeyFigureCard', (_message.Message,), dict(
  DESCRIPTOR = _KEYFIGURECARD,
  __module__ = 'CWAStats_pb2'
  # @@protoc_insertion_point(class_scope:CWAConfig.KeyFigureCard)
  ))
_sym_db.RegisterMessage(KeyFigureCard)

KeyFigure = _reflection.GeneratedProtocolMessageType('KeyFigure', (_message.Message,), dict(
  DESCRIPTOR = _KEYFIGURE,
  __module__ = 'CWAStats_pb2'
  # @@protoc_insertion_point(class_scope:CWAConfig.KeyFigure)
  ))
_sym_db.RegisterMessage(KeyFigure)

Statistics = _reflection.GeneratedProtocolMessageType('Statistics', (_message.Message,), dict(
  DESCRIPTOR = _STATISTICS,
  __module__ = 'CWAStats_pb2'
  # @@protoc_insertion_point(class_scope:CWAConfig.Statistics)
  ))
_sym_db.RegisterMessage(Statistics)


# @@protoc_insertion_point(module_scope)
